const Colors = {
  PRIMARY_DARK: "#2C2C2C",
  PRIMARY_LIGHT: "#E8DEF8",
  SECONDARY: "#FFC107",
  BACKGROUND: "#FFFFFF",
  TEXT_PRIMARY: "#000000",
  TEXT_SECONDARY: "#757575",
};

export default Colors;
