name: Test on Pull Request

on:
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: [KU]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Build Docker Container
        run: |
          docker build . -t test-shop-app
      - name: Clean up
        run: |
          docker image prune -a -f

